#ifndef __ARCHITECTURE_ENTITY_H__
#define __ARCHITECTURE_ENTITY_H__

#include <tchar.h>
#include <iostream>


typedef enum TYPEOFTILE{
	TOF_GRASS_LEFT				= 0,
	TOF_GRASS_RIGHT,
	TOF_GRASS_MIDDLE,
	TOF_GRASS_ONE_BUSH,
	TOF_GRASS_TOW_BUSH,
	TOF_GRASS_THREE_BUSH,

	TOF_CASTTLE					= 7,

	TOF_PIPE_HEAD_RIGHT,
	TOF_PIPE_BODY_RIGHT,
	TOF_PIPE_HEAD_DOWN,
	TOF_PIPE_HEAD_BODY_DOWN,
	TOF_PIPE_BODY_DOWN			= 12,

	TOF_CEMENT_PIPE,
	TOF_CEMENT_BARRIER_BLUE,
	TOF_CEMENT_BARRIER_RED,
	TOF_CEMENT_LANE_BLE,
	TOF_CEMENT_LANE_RED			= 17,

	TOF_CLOUND_ONE_MEMBER,
	TOF_CLOUND_TOW_MEMBER,
	TOF_CLOUND_THREE_MEMBER,

	TOF_MOUNTAIN_SMALL,
	TOF_MOUNTAIN_BIG,

	TOF_ELEVATOR,
	TOF_CASTLE_FLAG,

	TOF_FLAG,
	TOF_FLAG_POLE_HEAD,
	TOF_FLAG_POLE,
	TOF_FLAG_POLE_TAIL,

	TOF_BRICK_TILE
} TileStyle;

typedef enum TYPEOFENEMY{

	TOF_RED_MUSHROOM	=	0,
	TOF_BLUE_MUSHROOM	=	1,
	TOF_CARNIVOROUS_PLANT
} EnemyStyle;


typedef enum TYPEOFDATAINPUT{
	TODI_GIFT_BOX						= 1,
	TODI_BRICK							= 60,
	TODI_RED_MUSHROOM_BOX				= 3,
	TODI_GREEN_MUSHROOM_BOX				= 4,
	TODI_STARS							= 5,
	TODI_COININBOX						= 9,
	TODI_FLAG_POLE_TAIL					= 13,
	TODI_FLAG_POLE						= 14,
	TODI_FLAG_POLE_HEAD					= 15,
	TODI_GREEN_FLAG						= 16,
	TODI_GRASS_ONE_BRUSH				= 17,
	TODI_GRASS_DOUBLE_BRUSH				= 18,
	TODI_GRASS_TRIPPLE_BRUSH			= 19,
	TODI_CLOUND_ONE						= 20,
	TODI_CLOUND_DOUBLE					= 21,
	TODI_CLOUND_TRIPPLE					= 22,
	TODI_PIPE_HEAD						= 23,
	TODI_PIPE_HEAD_BODY					= 24,
	TODI_PIPE_BODY						= 25,
	TODI_CASTLE							= 26,
	TODI_LANDSCAPE						= 27,
	TODI_CEMENT							= 32,
	TODI_HEAD_MOUNTAIN					= 34,
	TODI_TAIL_MOUNTAIN					= 33,
	TODI_RECTANGLE						= -1,
	TODI_MUSHROOM						= 28,
	TODI_GREEN_TURTLE					= 30,

	TODI_GREEN_LANDSCAPE				= 53,
	TODI_BLUE_STAIR						= 49,
	TODI_COIN							= 55,
	TODI_RED_TURTLE						= 38,
	TODI_BLUE_CARNIVOROUSPLANTS			= 40,
	TODI_GREEN_CARNIVOROUSPLANTS		= 42,
	TODI_ELEVATOR_UP					= 44,
	TODI_ELEVATOR_DOWN					= 50,
	
	TODI_BRICK_TILE						= 2
} TODI;
#endif